/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import static project.TrainDetails.tAcB;
import static project.TrainDetails.tAcS;
import static project.TrainDetails.tEcoB;
import static project.TrainDetails.tEcoS;

/**
 *
 * @author Usman
 */
public class CustomerPortal extends javax.swing.JFrame {

    private PopupMenu initializeUI;
    String[] station={"Rahimyar Khan","Rorhi","Hyderabad","Karachi"};
    int from = 0, to = 0;
   // static int fare=0;
    TrainDetails t = new TrainDetails();
    // new javax.swing.JComboBox<station>();
    /**
     * Creates new form CustomerPortal
     * Customer after login comes into this class.
     * In this class customer can view their previous booking or can reset 
     * previous one and make new booking.
     * Customer can see train timings and available seats and berths
     * 
     */
    public CustomerPortal() {
       
        initComponents();
     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        jLabel38.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(242, 242, 242));
        jLabel38.setText("TRAINS SCHEDULE");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(190, 20, 210, 40);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(242, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Rahimyar Khan", "10:00 AM", "400"},
                {"Rorhi", "11:35 AM", "650"},
                {"Hyderabad", "4:20 PM", "1000"},
                {"Karachi", "6:45 PM", "1200"}
            },
            new String [] {
                "Stations", "Arrival Time", "Fare"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 540, 90);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transport527.jpg"))); // NOI18N
        jLabel37.setText("dss");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(0, 0, 560, 530);

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel10.setLayout(null);

        jLabel20.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(242, 242, 242));
        jLabel20.setText("Business Class");
        jPanel10.add(jLabel20);
        jLabel20.setBounds(6, 130, 191, 29);

        jLabel21.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(242, 242, 242));
        jLabel21.setText("Seats no.");
        jPanel10.add(jLabel21);
        jLabel21.setBounds(6, 165, 464, 26);

        jLabel22.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(242, 242, 242));
        jLabel22.setText("Berth no.");
        jPanel10.add(jLabel22);
        jLabel22.setBounds(10, 190, 450, 30);

        jLabel23.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(242, 242, 242));
        jLabel23.setText("Seat no:");
        jPanel10.add(jLabel23);
        jLabel23.setBounds(6, 305, 464, 20);

        jLabel24.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(242, 242, 242));
        jLabel24.setText("Berth no.");
        jPanel10.add(jLabel24);
        jLabel24.setBounds(10, 340, 464, 20);

        jLabel25.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(242, 242, 242));
        jLabel25.setText("Economy Class");
        jPanel10.add(jLabel25);
        jLabel25.setBounds(6, 262, 140, 19);
        jPanel10.add(jLabel26);
        jLabel26.setBounds(476, 331, 0, 0);

        jLabel27.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(242, 242, 242));
        jLabel27.setText("From");
        jPanel10.add(jLabel27);
        jLabel27.setBounds(110, 60, 160, 20);

        jLabel28.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(242, 242, 242));
        jLabel28.setText("To");
        jPanel10.add(jLabel28);
        jLabel28.setBounds(109, 108, 170, 19);

        jLabel29.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(242, 242, 242));
        jLabel29.setText("From");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(6, 63, 50, 19);

        jLabel30.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(242, 242, 242));
        jLabel30.setText("To");
        jPanel10.add(jLabel30);
        jLabel30.setBounds(6, 108, 40, 19);

        jLabel31.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(242, 242, 242));
        jLabel31.setText("Total Cost");
        jPanel10.add(jLabel31);
        jLabel31.setBounds(6, 396, 170, 20);

        jLabel32.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(242, 242, 242));
        jLabel32.setText("Ticket ID");
        jPanel10.add(jLabel32);
        jLabel32.setBounds(6, 13, 120, 19);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/people.jpg"))); // NOI18N
        jPanel10.add(jLabel36);
        jLabel36.setBounds(0, 0, 560, 530);

        jTabbedPane1.addTab("tab4", jPanel10);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("From ");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(52, 73, 78, 42);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("To");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(369, 86, 16, 16);

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0,80
        ));
        jComboBox1.setForeground(new java.awt.Color(242, 242, 242));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rahimyar Khan", "Rorhi", "Hyderabad", "Karachi" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(136, 81, 100, 22);

        jComboBox2.setBackground(new java.awt.Color(0, 0, 0,80
        ));
        jComboBox2.setForeground(new java.awt.Color(242, 242, 242));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rahimyar Khan", "Rorhi", "Hyderabad", "Karachi" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(408, 81, 90, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Seats");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(48, 173, 70, 30);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0,80));
        jTextField1.setForeground(new java.awt.Color(242, 242, 242));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(128, 170, 100, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Berths");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(346, 166, 70, 40);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0,80));
        jTextField2.setForeground(new java.awt.Color(242, 242, 242));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 1, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(418, 170, 100, 30);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(242, 242, 242));
        jButton3.setText("Calculate Bill");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(50, 410, 121, 26);

        jTextField3.setBackground(new java.awt.Color(0, 0, 0,80));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3);
        jTextField3.setBounds(220, 410, 96, 23);

        jLabel6.setFont(new java.awt.Font("MS Mincho", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Business Class");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(236, 133, 150, 20);

        jLabel7.setFont(new java.awt.Font("MS Mincho", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Economy Class");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(240, 230, 150, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Seats");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(50, 280, 60, 40);

        jTextField4.setBackground(new java.awt.Color(0, 0, 0,80
        ));
        jTextField4.setForeground(new java.awt.Color(242, 242, 242));
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 1, true));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField4);
        jTextField4.setBounds(132, 278, 100, 30);

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Berths");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(342, 280, 70, 30);

        jTextField5.setBackground(new java.awt.Color(0, 0, 0,80));
        jTextField5.setForeground(new java.awt.Color(242, 242, 242));
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 242, 242), 1, true));
        jPanel3.add(jTextField5);
        jTextField5.setBounds(420, 278, 100, 30);

        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("•Business class will cost 15% extra.");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 442, 193, 27);

        jLabel39.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(242, 242, 242));
        jLabel39.setText("Choose Your Destination");
        jPanel3.add(jLabel39);
        jLabel39.setBounds(150, 20, 330, 30);

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(242, 242, 242));
        jButton6.setText("Reset");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(420, 410, 90, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patterns527.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(0, -20, 560, 560);

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel11.setText("Seats");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 280, 64, 19);

        jPanel6.setBackground(new java.awt.Color(0, 204, 204,80));

        jLabel15.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel15.setText("Business Class");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 190, 190, 70);

        jLabel13.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel13.setText("Seats");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(330, 280, 48, 27);

        jLabel14.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel14.setText("Berths");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(440, 280, 60, 27);

        jPanel7.setBackground(new java.awt.Color(255, 204, 51,80));

        jLabel16.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel16.setText("Economy Class");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7);
        jPanel7.setBounds(330, 190, 209, 70);

        jTextField6.setBackground(new java.awt.Color(0, 0, 0,80
        ));
        jTextField6.setForeground(new java.awt.Color(242, 242, 242));
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(jTextField6);
        jTextField6.setBounds(444, 310, 90, 18);

        jTextField7.setBackground(new java.awt.Color(0, 0, 0,80));
        jTextField7.setForeground(new java.awt.Color(242, 242, 242));
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField7);
        jTextField7.setBounds(330, 310, 90, 18);

        jTextField8.setBackground(new java.awt.Color(0, 0, 0,80));
        jTextField8.setForeground(new java.awt.Color(242, 242, 242));
        jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField8);
        jTextField8.setBounds(124, 310, 90, 18);

        jTextField9.setBackground(new java.awt.Color(0, 0, 0,80));
        jTextField9.setForeground(new java.awt.Color(242, 242, 242));
        jTextField9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField9);
        jTextField9.setBounds(20, 310, 80, 18);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255,80));
        jPanel8.setLayout(null);

        jLabel17.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel17.setText(" Available Berths and Seats");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(0, -16, 310, 80);

        jPanel5.add(jPanel8);
        jPanel8.setBounds(100, 114, 310, 50);

        jLabel18.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel18.setText("Berths");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(124, 280, 70, 19);

        jLabel34.setFont(new java.awt.Font("MS Mincho", 1, 24)); // NOI18N
        jLabel34.setText("Express Train");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(170, 10, 192, 59);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transport (2).jpg"))); // NOI18N
        jLabel35.setText("jLabel35");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(0, 0, 560, 530);

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -30, 560, 570));

        jPanel4.setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Timings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(6, 168, 130, 50);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 242, 242));
        jButton2.setText("Destination");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(6, 236, 130, 52);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Welcome "+CustomerLogin.name);
        jPanel4.add(jLabel2);
        jLabel2.setBounds(6, 6, 290, 50);

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(242, 242, 242));
        jButton4.setText("Information");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(6, 306, 130, 53);

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(242, 242, 242));
        jButton5.setText("Booking Slip");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(6, 377, 130, 52);

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(242, 242, 242));
        jButton7.setText("Sign Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(6, 447, 130, 50);

        jLabel40.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(242, 242, 242));
        jLabel40.setText("To Express Train Booking");
        jPanel4.add(jLabel40);
        jLabel40.setBounds(10, 70, 280, 50);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/621d1c8192a9c1000164de17.jpg"))); // NOI18N
        jLabel33.setText("jLabel33");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(3, -4, 300, 530);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        // new javax.swing.JComboBox<station>();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //information 
        Connection con;
        Statement stmt;
        String url="jdbc:mysql://localhost:3306/customer?characterEncoding=utf8";
        var query = "SELECT * FROM traindetails";
        PreparedStatement st = null;//=con.prepareStatement("insert into customer(cid,cname,cemail,cpass,cgender,cno) values (?,?,?,?,?,?)");;
        ResultSet rs;

        try
	{
            con= DriverManager.getConnection(url,"root","root");
            stmt=con.createStatement();
            st=con.prepareStatement(query);
            rs= st.executeQuery(); while (rs.next()){

            //System.out.println("Check ?? ");
            jTextField9.setText("Available: "+rs.getString(2));
            jTextField8.setText("Available: "+rs.getString(3));                  
            jTextField7.setText("Available: "+rs.getString(4));
            jTextField6.setText("Available: "+rs.getString(5));

        }
	}catch(SQLException e)
	{
            System.out.println("IN CONN CLASS "+ e);
	}
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //calculate bill
        int t1,t2,t3,t4;
        TrainDetails.fare=0;
        t1= parseInt(jTextField1.getText());//Ac Seats
        t2= parseInt(jTextField2.getText()); //Ac Berth
        t3= parseInt(jTextField4.getText()); //Eco Seats
        t4= parseInt(jTextField5.getText()); //Eco Berth
        TrainDetails.tAcS-=t1;
        TrainDetails.tAcB-=t2;
        TrainDetails.tEcoS-=t3;
        TrainDetails.tEcoB-=t4;
        int f;
        f=t.costCalc(from, to,t1,t2,t3,t4);
        
        Random rand = new Random();
        int randno = rand.nextInt(100000 );
        
        String from1 = (String ) jComboBox1.getSelectedItem();
        String to2= (String ) jComboBox2.getSelectedItem();
        Conn conn = new Conn(); 
        String query1="UPDATE traindetails SET tAcS=('"+TrainDetails.tAcS+"'), tAcB=('"+TrainDetails.tAcB+"'),tEcoS=('"+TrainDetails.tEcoS+"') ,tEcoB=('"+TrainDetails.tEcoB+"') WHERE sno=0";
        String query2="UPDATE customer SET cFrom=('"+from1+"'), cTo=('"+to2+"'), AcSeats=('"+t1+"'), AcBerths=('"+t2+"'), EcoSeats=('"+t3+"') , EcoBerths= ('"+t4+"') , fare=('"+f+"'), ticketid= ('"+randno+"') where cname=('"+CustomerLogin.name+"')  ";
        try
	{
            conn.s.executeUpdate(query1);
            conn.s.executeUpdate(query2);
            JOptionPane.showMessageDialog(null, "updated");
            ResultSet rs = conn.s.executeQuery("select * from traindetails");
            //st=conn.c.prepareStatement(TOOL_TIP_TEXT_KEY);
           
            if(rs.next()){
                tAcS=rs.getInt(2);
                tAcB=rs.getInt(3);
                tEcoS=rs.getInt(4);
                tEcoB=rs.getInt(5);
                
            }
        
        }catch(SQLException e)
	{
            System.out.println("IN CONN CLASS of customerportail "+ e);
	}
        
         from= jComboBox1.getSelectedIndex();
         to =jComboBox2.getSelectedIndex();
         t.costCalc(from, to,t1,t2,t3,t4); //calculation method
         jTextField3.setText(""+TrainDetails.fare);
         
         if(evt.getSource()==jButton6){
            TrainDetails.fare=0;
           
            jTextField3.setText(""+TrainDetails.fare);
           
        }
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
               
        try{
            String selected = (String) jComboBox1.getSelectedItem();
            System.out.print(selected);
            
            jTabbedPane1.setSelectedIndex(1);
            Conn conn= new Conn();
            PreparedStatement st;
            st = conn.c.prepareStatement("select  * from customer");
            //ResultSet rs = conn.s.executeQuery("select * from customer");
            ResultSet rs;
            rs= st.executeQuery();
            //ts= st.executeQuery();
            //st=conn.c.prepareStatement(TOOL_TIP_TEXT_KEY);
           while(rs.next()){
               if(rs.getString(1).equals(CustomerLogin.name))
            {
                System.out.println(getString(1)+" check "+getString(6));
                System.out.println(" if;;; "+rs.getString(2) + " _--- "+rs.getInt(8));
              
                jLabel27.setText(rs.getString(6));
                jLabel28.setText(rs.getString(7));
                jLabel31.setText("Total Cost: "+rs.getInt(12));
                jLabel32.setText("Ticket ID: "+rs.getInt(13));
                 var seat=" ";
                for(int i=TrainDetails.tAcS-rs.getInt(8);i<TrainDetails.tAcS;i++){
                seat+=(" "+i);
                }
                jLabel21.setText("Seats No. : "+seat);
                 seat="";
                for(int i=TrainDetails.tAcB-rs.getInt(9);i<TrainDetails.tAcB;i++){
                seat+=(" "+i);
                }
                jLabel22.setText("Berths No. : "+seat);
                seat="";
                for(int i=TrainDetails.tEcoS-rs.getInt(10);i<TrainDetails.tEcoS;i++){
                seat+=(" "+i);                
                }
                jLabel23.setText("Seats No. : "+seat);
                seat="";
                for(int i=TrainDetails.tEcoB-rs.getInt(11);i<TrainDetails.tEcoB;i++){
                    seat+=(" "+i);
                }
                jLabel24.setText("Berth No. : "+seat);
           
                
            }
           }
            
             }
            catch(NumberFormatException ex){
                //System.out.print("ex"+" Handled");

            } catch (SQLException ex) {
            Logger.getLogger(CustomerPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_jButton5ActionPerformed
 
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       try{
          Conn con = new Conn();
          //PreparedStatement st= con.c.prepareStatement("selet ");
           String query2="UPDATE customer SET cFrom=('"+null+"'), cTo=('"+null+"'), AcSeats=('"+0+"'), AcBerths=('"+0+"'), EcoSeats=('"+0+"') , EcoBerths= ('"+0+"') , fare=('"+0+"'), ticketid= ('"+000000+"') where cname=('"+CustomerLogin.name+"')  ";
       con.s.execute(query2);
          
        
       }
       catch(Exception e){
           
       }
        if(evt.getSource()==jButton6){
            TrainDetails.fare=0;
            jTextField3.setText(""+TrainDetails.fare);
        }
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        setVisible(false);
         new CustomerLogin().setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void addStation(String rahimyar_Khan, String _am, double d) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Object jComboBox1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String toSring(int t1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
